---
title: "Setup"
editor_options:
  chunk_output_type: console
---

Please read the following setup information prior to the workshop beginning:

# Environment setup

A Docker image is available containing RStudio and JupyterLab with dependencies already set up (`quay.io/sagc/rstomics`).

There are two main options to use this image:

## Run docker locally

This is recommended if you already have Docker set up and would like to run
everything on your own hardware.

1. Pull the image: `docker pull quay.io/sagc/rstomics`
2. Run container, exposing ports for rstudio and jupyter, optionally bind mounting storage on your local machine, e.g.

```{bash, eval=FALSE}
#!/bin/bash

BIND_PATH=/my/local/storage

docker run \
    --rm -ti \
    -p 8787:8787 \
    -p 8888:8888 \
    -v ${BIND_PATH}:/root/data quay.io/sagc/rstomics
```

> If you use local bind paths, make sure that any data files you wish to retain
> are created in the bind mount (in the above script, this will be visible in the container at /root/data)

### Accessing the environment

Once the container is running:

- The RStudio server can be accessed on port 8787: [http://127.0.0.1:8787](http://127.0.0.1:8787)
- The JupyterLab server can be accessed on port 8888: [http://127.0.0.1:8888](http://127.0.0.1:8888)

Use passphrase `abacbs24` and username `root` if required.

## Run docker in cloud (Nectar)

If you'd like to run a cloud instance of the container, we will provide you with
an IP address where the container is being hosted. Please ask an instructor for assistance.

You'll just need an internet-connected device to be able to access your instance.

Log in as per the [Accessing the environment](#accessing-the-environment) section above, 
substituting the the IP address with the one provided on the day.

> Please *download* any modified files you wish to keep before the end of the day,
> as the cloud instance will be destroyed after the day of the workshop!


## Run manually (not recommended)

If you want to set up an environment from scratch, please refer to the Dockerfile
for required dependencies.

Please note that due to the short amount of time allocated we will not be able to 
help diagnose setup issues if you choose this method.

> Please note that StereoPy **requires** Python 3.8, it is not compatible with newer Python versions.

# Obtaining the code

This website is implemented with `workflowr` and can be cloned into a location
of your preference. Navigate to a suitable location, and clone `https://github.com/sagc-bioinformatics/abacbs2024_workshop.git`.

> If needed you can access a terminal from within RStudio or JupyterLab.

e.g:

```
#!/bin/bash

# in the local docker setup above, this location is bind mounted to the host
cd data/

# obtain the code for this workshop
git clone https://github.com/sagc-bioinformatics/abacbs2024_workshop.git
```

# Obtaining the data

Once you have cloned the repository, navigate to RStudio, and run the download workbook
[(00_download.Rmd)](00_download.html) to download the data files.

